[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = true

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

[UI]
# Name of the app and chatbot.
name = "Chatbot"

# Description of the app and chatbot. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = true

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
custom_css = "style.css"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    background = "#f7f8fa"  # --van-gray-1
    paper = "#ffffff"  # --van-white

    [UI.theme.light.primary]
        main = "#1989fa"  # --van-blue
        dark = "#dcdee0"  # --van-gray-4
        light = "#ebedf0"  # --van-gray-3

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
    background = "#323233"  # --van-gray-8
    paper = "#646566"  # --van-gray-7

    [UI.theme.dark.primary]
        main = "#07c160"  # --van-green
        dark = "#969799"  # --van-gray-6
        light = "#c8c9cc"  # --van-gray-5


[meta]
generated_by = "0.7.2"
